### ISSUE TITLE
No color on node 12 server

### ISSUE THREAD

**Issue by bohendo** [pinojs/pino-pretty#220]
Noticed after upgrading to pino-pretty 6.0.0 so some problem was probably introduced by colorette in PR #218 

In my utils I have:
```
import pino from "pino";
import prettifier from "pino-pretty";

export const getLogger = (level = "warn"): pino.Logger => pino({
  level,
  prettyPrint: {
    colorize: true,
    ignore: "pid,hostname,module",
    messageFormat: `[{module}] {msg}`,
    translateTime: true,
  },
  prettifier,
});
```

Then on my server I have:
```
import { getLogger } from "@valuemachine/utils";

import { env } from "./env";

const log = getLogger(env.logLevel).child({ module: "Utils" });
log.info(`Logger loaded!`);
```

Result is white text:
![Screenshot from 2021-08-24 13-53-14](https://user-images.githubusercontent.com/8527067/130583064-61eb1552-a8fd-48b4-a86c-456f8f4113b7.png)

Downgrading to pino-pretty 5.1.3 results in colored output:
![Screenshot from 2021-08-24 13-55-28](https://user-images.githubusercontent.com/8527067/130583470-8ee838ff-d2f4-4e1a-82eb-d934f7a1a15b.png)

This server is based on the `node:12.16.1-alpine3.11` docker image so it shouldn't be affected by colorette's problems w node v13

**Comment by kibertoad** [comment]
@jorgebucaran

**Comment by kibertoad** [comment]
@jorgebucaran Wonder if env.COLOR_TERM check needs to be added to colorette. any ideas what term alpine uses?

**Comment by jorgebucaran** [comment]
I'm not familiar with `COLOR_TERM`, but I think Alpine uses xterm.

**Comment by jorgebucaran** [comment]
Running `docker run -it node:12.16.1-alpine3.11 sh` and trying Colorette in the Node REPL produced the desired output.

**Comment by kibertoad** [comment]
@bohendo Could you share contents of your process.env when running under that environment?

**Comment by kibertoad** [comment]
@bohendo Ping? We'd love to fix this issue, but we need to understand which particular env values we could use in your particular case, looks like the one we already use are not sufficient in your environment.

**Comment by bohendo** [comment]
> Could you share contents of your process.env when running under that environment?

```

**Comment by bohendo** [comment]
Oh wow, I just noticed in the env: `"NODE_VERSION": "14.15.4"` probably bc this server uses nodemon & ts-node in dev-mode which is where I'm seeing the lack of color. So this could actually be an issue w colorette not playing nice w node versions >12

fwiw, [the command being executed](https://github.com/bohendo/valuemachine/blob/main/modules/server/ops/entry.sh#L23) is:
```
  exec ./node_modules/.bin/nodemon \
    --delay 1 \
    --exitcrash \
    --ignore ./*.test.ts \
    --ignore ./*.swp \
    --legacy-watch \
    --polling-interval 1000 \
    --watch src \
    --exec "node -r ts-node/register" \
    src/entry.ts
```

**Comment by jorgebucaran** [comment]
I suggest opening an issue on Colorette so we can discuss your suggestion.

**Comment by yuser1337** [comment]
You can use something like:

`FORCE_COLOR=1 pino-pretty -c `

My full example:
`ts-node-dev --respawn --poll -r tsconfig-paths/register src/server.ts | FORCE_COLOR=1 pino-pretty -c -t -l`

It sucks obviously

**Comment by mcollina** [comment]
I'm currently suffering from the same problem. 

I have

```
TERM=screen-256color
```

in my env.

**Comment by kibertoad** [comment]
@mcollina Will be fixed in the nearby future upstream, we've already discussed path forward with @jorgebucaran in https://github.com/jorgebucaran/colorette/issues/42

That's an interesting TERM, will check if we need to expand our condition list.

**Comment by kibertoad** [comment]
@mcollina I've checked colorette code, and it actually should work out-of-the-box with such ENV, unless you have "env.NO_COLOR"

**Comment by jorgebucaran** [comment]
Which part: `process.stdout.isTTY`? Yes, IIRC that's how we check if we're running through a pipe.

**Comment by mcollina** [comment]
You should use https://nodejs.org/dist/latest-v16.x/docs/api/tty.html#tty_tty_isatty_fd with `fd = 1` instead. process.stdout is not a TTY inside worker_threads.

**Comment by mcollina** [comment]
This should be fixed in the latest version of colorette, let us know.

**Comment by bohendo** [comment]
I've upgraded & am now using pino@6.13.2 & pino-pretty@7.0.0 & sadly, I still see the same lack of color as before.

Fwiw, `process.stdout.isTTY` is undefined and `process.stdout.fd` equals `1`

I've updated my server's base image to [node:14.17.6-alpine3.14](https://github.com/bohendo/valuemachine/blob/78df630724cf7f76b096954c4d8a0d13dc72a80f/modules/server/ops/Dockerfile#L1)

I've added `export FORCE_COLOR=1` to my [server's entry script](https://github.com/bohendo/valuemachine/blob/78df630724cf7f76b096954c4d8a0d13dc72a80f/modules/server/ops/entry.sh#L21) so now I have color & I'm content w this solution. If you still want to fix it, let me know what other info you need & I'll do whatever I can to help.

**Comment by mcollina** [comment]
cc @kibertoad

**Comment by mcollina** [comment]
I think the problem is on our end as we do not enforce the colorize option properly.. that should take over any checks for TTY.

**Comment by kibertoad** [comment]
I know. I'm waiting for https://github.com/jorgebucaran/colorette/issues/42 to land in 2.0.0

**Comment by bohendo** [comment]
I've tested & confirmed that this issue is now 100% resolved as of version 7.0.1. Great job, thank you!
